Add caseSensitive parameter on the InlineSyntax constructor
dart-lang/markdown pull request #400
Opened 2022-03-25 06:25 UTC by chenzhiguang

Fix: https://github.com/dart-lang/markdown/issues/367

2022-04-01 21:36 UTC, srawlins requested changes
Can you add a few tests which might indicate how this would be used? Thanks for the help!

2022-04-01 21:36 UTC, srawlins commented on lib/src/inline_parser.dart
> +  InlineSyntax(String pattern, {int? startCharacter, bool? caseSensitive})
Let's make this a non-nullable bool, defaulting to true.

2022-04-11 18:04 UTC, chenzhiguang commented
> Can you add a few tests which might indicate how this would be used? Thanks for the help!

Sorry, just saw this comment, I will add some tests later soon.

2022-04-12 05:38 UTC, srawlins approved these changes
Thanks!

2022-04-12 05:38 UTC, merged