Enable require_trailing_commas lint rule
dart-lang/markdown pull request #419
Opened 2022-04-17 17:28 UTC by chenzhiguang

Add this optional trailing commas to parameter lists to get good formatting. It is also recommended in [Flutter: Using trailing commas
](https://docs.flutter.dev/development/tools/formatting#using-trailing-commas)

2022-04-18 18:37 UTC, kevmoo commented
I like this lint, but since @srawlins is the primary maintainer here, I'll let him comment!

2022-04-19 15:42 UTC, srawlins reviewed
I like many of the changes that this induces, but I strongly dislike some of them. What do you say to keeping many of these changes (I can mark the ones to revert), and we do not change analysis_options.yaml?

2022-04-19 15:42 UTC, srawlins commented on benchmark/benchmark.dart
> +    "${'=' * ((time * 20).toInt())}",
I am not a fan of this lint rule. For cases like this.

I am a fan of adding trailing commas to argument lists when there is more than one argument, and they span more than 1 line without the comma.

This change here is harder for me to read though.

2022-04-19 15:42 UTC, srawlins commented on bin/markdown.dart
> +    ..addOption(
I like this change though.

2022-04-19 15:42 UTC, srawlins commented on bin/markdown.dart
> +  );
Again, I don't think this is helpful.

2022-04-19 15:54 UTC, chenzhiguang commented
> I like many of the changes that this induces, but I strongly dislike some of them. What do you say to keeping many of these changes (I can mark the ones to revert), and we do not change analysis_options.yaml?

I do not like some of them too. 

Yep. let me remove the rule from analysis_options.yaml, and reformat it.

2022-04-19 16:28 UTC, srawlins requested changes
The vast majority of the changes improve readability I think.

Just a few where I think the change is much worse.

2022-04-19 16:28 UTC, srawlins commented on lib/src/block_parser.dart
> +  r'^[ ]{0,3}\|?([ \t]*:?\-+:?[ \t]*\|)+([ \t]|[ \t]*:?\-+:?[ \t]*)?$',
I think this should be reverted.

2022-04-19 16:28 UTC, srawlins commented on lib/src/inline_parser.dart
> +      final resolved = linkResolver(
I think this should be reverted. It just feels very strange to me in cases like this where there is only one parameter...

2022-04-19 16:28 UTC, srawlins commented on tool/stats_lib.dart
> +String get toolDir => p.dirname(
I think this should be reverted.

But this change I think indicates a smell; this arrow-function should probably be a function body with a local variable, like a variable for the `reflect` result...

2022-04-19 16:28 UTC, srawlins commented on tool/update_emojis.dart
> +        ),
I think this should be reverted.

2022-04-19 16:28 UTC, srawlins commented on tool/update_emojis.dart
> +''',
I think this should be reverted.

2022-04-19 16:28 UTC, srawlins commented on tool/update_emojis.dart
> +    'ignoring ${ignored.length}: ${ignored.join(', ')}.',
I think this should be reverted.

2022-04-19 16:50 UTC, chenzhiguang commented
How about close this PR?  I have just created a new [PR](https://github.com/dart-lang/markdown/pull/419) which has much fewer changes. please have a look.

2022-04-19 19:59 UTC, srawlins commented
Closing in favor of #420

2022-04-19 19:59 UTC, closed without merging