Improve BlockquoteSyntax
dart-lang/markdown pull request #479
Opened 2022-10-28 15:12 UTC by chenzhiguang

Strictly improves the test coverage.

2022-10-28 15:16 UTC, chenzhiguang commented on tool/gfm_stats.json
> +  "215": "loose",
It will be **strict** after #478 is merged

2022-10-28 23:39 UTC, srawlins requested changes
Nice little fix! One nit.

2022-10-28 23:39 UTC, srawlins commented on lib/src/block_syntaxes/blockquote_syntax.dart
> +        // A block quote marker consists of a `>` together with a optional
nit: "an optional"

2022-10-29 02:14 UTC, chenzhiguang commented on lib/src/block_syntaxes/blockquote_syntax.dart
> +        // A block quote marker consists of a `>` together with a optional
Fixed

2022-10-29 16:18 UTC, chenzhiguang commented
Rebased

2022-11-04 05:29 UTC, kevmoo commented
@chenzhiguang – please rebase on `master` – we now have `flutter_markdown` validation in place

If there are breaks there, we'll have to dig to see what's expected/intended.

2022-11-04 05:53 UTC, chenzhiguang commented
Rebased

2022-11-04 17:30 UTC, chenzhiguang commented
## Benchmark

### Before

![Screenshot 2022-11-04 at 18 01 48](https://user-images.githubusercontent.com/5637609/200033636-67a33146-2a4a-40c3-b0b5-6878492b11ac.png)

### After
![Screenshot 2022-11-04 at 18 29 16](https://user-images.githubusercontent.com/5637609/200039032-bc8b14a4-c663-4a74-9837-b424d93bf2b0.png)

2022-11-08 17:13 UTC, kevmoo requested changes

2022-11-08 17:13 UTC, kevmoo commented on lib/src/test.dart
> +import '../markdown.dart';
Should delete this, right @chenzhiguang ?

2022-11-08 17:22 UTC, kevmoo approved these changes
:shipit:

2022-11-09 18:22 UTC, srawlins approved these changes
❤️

2022-11-09 18:22 UTC, merged