Fix `RangeError` hazards in links
dart-lang/markdown pull request #624
Opened 2024-10-15 06:25 UTC by andrechalella

This fixes #623 as well as https://github.com/flutter/flutter/issues/155020.

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

2024-10-15 20:42 UTC, srawlins requested changes

2024-10-15 20:43 UTC, andrechalella commented on CHANGELOG.md
> +* Fix several `RangeError` hazards in links (#623).
Ok, will do.

2024-10-15 20:49 UTC, andrechalella commented on CHANGELOG.md
> +* Fix several `RangeError` hazards in links (#623).
Done, I guess. Can you take a look? I'm kinda new to this.

2024-10-16 14:30 UTC, srawlins approved these changes
Looks great, thanks for the fixes!!

2024-10-16 14:30 UTC, merged